src/IContestPro.Web.Mvc/Controllers/BlogsController.cs
using System;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using Abp.AutoMapper;
using Abp.Dependency;
using Abp.Domain.Uow;
using Abp.Runtime.Session;
using Abp.Web.Mvc.Alerts;
using IContestPro.AssetUpload;
using IContestPro.AssetUpload.Dto;
using IContestPro.Authorization;
using IContestPro.Blog;
using IContestPro.Blog.Dto;
using IContestPro.Contest.ContestType.Dto;
using IContestPro.Contest.Dto;
using IContestPro.Helpers;
using Microsoft.AspNetCore.Mvc;
using IContestPro.LeaderBoard;
using IContestPro.Status;
using IContestPro.Web.Helpers.AlertExtension;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace IContestPro.Web.Controllers
{
    public class BlogsController : BaseController
    {
        private readonly IBlogAppService _blogAppService;
        private readonly IAssetUploadAppService _assetUploadAppService;
        private readonly IStatusAppService _statusAppService;

        public BlogsController(IIocResolver iocResolver, IBlogAppService blogAppService, IAssetUploadAppService assetUploadAppService, IStatusAppService statusAppService) : base(iocResolver)
        {
            _blogAppService = blogAppService;
            _assetUploadAppService = assetUploadAppService;
            _statusAppService = statusAppService;
        }

        #region Admin
        // GET
        [AbpMvcAuthorize(Permissions = new []{PermissionNames.Pages_Admin})]
        public async Task<IActionResult> IndexAdmin(int page = 1, int pageSize = 10, string status = "All")
        {
                ViewBag.PageSize = pageSize;
                ViewBag.Page = page;
                ViewBag.Status = status;
                var items = await _blogAppService.GetAllByStatusAsync(page,pageSize, status);
                return View(items); 
        } 
       
        [HttpPost]
        [UnitOfWork]
        [AbpMvcAuthorize(Permissions = new []{PermissionNames.Pages_Admin})]
        public  async Task<IActionResult> Delete(EntityDto model)
        {
            await _blogAppService.Delete(model);
            AddAlertMessage(new AlertMessageCustom(AlertType.Success, "Contest type deleted successfully."));
            return RedirectToAction("Index");
        } 
       
        [AbpMvcAuthorize(Permissions = new []{PermissionNames.Pages_Admin})]
        public  async Task<IActionResult> Create()
        {
            return View(new CreateBlogDto());
        } 
        [HttpPost]
        [UnitOfWork]
        [AbpMvcAuthorize(Permissions = new []{PermissionNames.Pages_Admin})]
        public  async Task<IActionResult> Create(CreateBlogDto model, IFormFile file, bool activateNews)
        {
            ViewBag.ActivateNews = activateNews;
            if (file == null || file.Length == 0)
            {
                AddAlertMessage(new AlertMessageCustom(AlertType.Warning, "Please upload a file."));
                return View(model); 
            }
            if (file.ContentType.IndexOf("image", StringComparison.OrdinalIgnoreCase) < 0)
            {
                AddAlertMessage(new AlertMessageCustom(AlertType.Success, "Please select only image file."));
                return View(model);
            }
            var uploaded = _assetUploadAppService.CropAndUploadImage(new UploadDto{File = file, Path = "images/uploads"}, 650, 300);
            model.Image = uploaded.FileName;

            model.Permalink = model.Title.GeneratePermalink();
            var itemExists = await _blogAppService.GetByTitle(model.Title);
            if (itemExists != null)
            {
                AddAlertMessage(new AlertMessageCustom(AlertType.Danger, $"News with the title '{itemExists.Title}' already exists."));
                return View(model); 
            }
            var item = await _blogAppService.Create(model, activateNews);
            if (item.Id > 0)
            {
                AddAlertMessage(new AlertMessageCustom(AlertType.Success, "News created successfully."));
                return RedirectToAction("DetailsAdmin", new {id = item.Id});
            }
            AddAlertMessage(new AlertMessageCustom(AlertType.Danger, "Error occurred while creating news."));
            return View(model);
        } 
        [AbpMvcAuthorize(Permissions = new []{PermissionNames.Pages_Contest_Update})]
        public  async Task<IActionResult> Edit(int id)
        {
            var itemGotten = await _blogAppService.Get(new EntityDto{Id = id});
            if (itemGotten == null)
            {
                AddAlertMessage(new AlertMessageCustom(AlertType.Warning, "The blog you are looking for was not found."));
                return RedirectToAction("IndexAdmin");
            }

            ViewBag.Status = await _statusAppService.Get(new EntityDto{Id = itemGotten.StatusId});
            return View(itemGotten.MapTo<EditBlogDto>());
        }
        
        [HttpPost]
        [UnitOfWork(false)]
        [AbpMvcAuthorize(Permissions = new []{PermissionNames.Pages_Contest_Update})]
        public  async Task<IActionResult> Edit(EditBlogDto model, IFormFile file)
        {
            ViewBag.Status = await _statusAppService.Get(new EntityDto{Id = model.StatusId});
            if (file != null)
            {
                if (file.Length == 0)
                {
                    AddAlertMessage(new AlertMessageCustom(AlertType.Success, "Please upload a file."));
                    return View(model); 
                }

                if (file.ContentType.IndexOf("image", StringComparison.OrdinalIgnoreCase) < 0)
                {
                    AddAlertMessage(new AlertMessageCustom(AlertType.Success, "Please select only image file."));
                    return View(model);
                
                }
                var uploaded = _assetUploadAppService.CropAndUploadImage(new UploadDto{File = file, Path = "images/uploads"}, 650, 300);
                _assetUploadAppService.Delete(new DeleteAssetDto{Path = $"/images/uploads/{model.Image}"});
                model.Image = uploaded.FileName;
            }
           
            var savedItem = await _blogAppService.Update(model.MapTo<BlogDto>());
            if (savedItem.Id > 0)
            {
                AddAlertMessage(new AlertMessageCustom(AlertType.Success, "Blog edited successfully."));
                return RedirectToAction("DetailsAdmin", new {id = savedItem.Permalink});
            }
             AddAlertMessage(new AlertMessageCustom(AlertType.Danger, "Error occurred while editing blog."));
            return View(model);
        }
        
        
        [AbpMvcAuthorize(Permissions = new []{PermissionNames.Pages_Admin})]
        public async Task<IActionResult> DetailsAdmin(string id, int page = 1, int pageSize = 50)
        {
            var offset = (page - 1) * pageSize;  
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            var item = await _blogAppService.GetDetailsByPermalink(id, new PagedResultRequestDto{SkipCount = offset, MaxResultCount = pageSize});
            return View(item); 
        } 
        [HttpPost]
        [UnitOfWork]
        [AbpMvcAuthorize(Permissions = new []{PermissionNames.Pages_Admin, PermissionNames.Pages_Sponsor})]
        public  async Task<IActionResult> ChangeStatus(UpdateStatusDto model, string permalink)
        {
            var savedItem = await _blogAppService.UpdateStatusAsync(model);
            if (savedItem.Id > 0)
            {
                AddAlertMessage(new AlertMessageCustom(AlertType.Success, "Blog updated successfully."));
                return RedirectToAction("DetailsAdmin", new {id = permalink});
            }
            AddAlertMessage(new AlertMessageCustom(AlertType.Danger, "Error occurred while updating contest."));
            return RedirectToAction("DetailsAdmin", new {id = permalink});
        }
        #endregion
        
        
        #region PublicPages
        public async Task<IActionResult> Index(int page = 1, int pageSize = 10)
        {
            ViewBag.ActiveOurBlog = "active";
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            var items = await _blogAppService.GetAllByStatusAsync(page, pageSize, AppConsts.StatusActive);
            return View(items); 
        } 
        public async Task<IActionResult> Tag(string id, int page = 1, int pageSize = 10)
        {
            ViewBag.ActiveOurBlog = "active";
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            ViewBag.Tag = id;
            var items = await _blogAppService.SearchBlogsByTag(id, page, pageSize);
            return View(items); 
        } 
        
        /// <summary>
        /// This method fetches the details of a news
        /// </summary>
        /// <param name="id">The permalink of the news</param>
        /// <param name="page">Current page</param>
        /// <param name="pageSize">Size of the page</param>
        /// <returns>Action result</returns>
        
        public async Task<IActionResult> Details(string id, int page = 1, int pageSize = 50)
        {
            ViewBag.ActiveOurBlog = "active";
            var offset = (page - 1) * pageSize;  
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            var item = await _blogAppService.GetDetailsByPermalink(id, new PagedResultRequestDto{SkipCount = offset, MaxResultCount = pageSize});
            return View(item); 
        } 
        [HttpPost]
        [UnitOfWork]
        public  async Task<IActionResult> NewBlogResponse(CreateBlogResponseDto model, string permalink)
        {
            var item = await _blogAppService.CreateResponse(model);
            if (item.Id > 0)
            {
                AddAlertMessage(new AlertMessageCustom(AlertType.Success, "Comment posted successfully."));
                return RedirectToAction("Details", new {id = permalink});
            }

src/IContestPro.Web.Mvc/Views/Blogs/Create.cshtml
@using IContestPro.Blog.Dto
@using IContestPro.Cookie
@using IContestPro.Web.Startup
@using Microsoft.AspNetCore.Hosting;
@model IContestPro.Blog.Dto.CreateBlogDto
@inject IHostingEnvironment HostingEnvironment;
@inject ICookieAppService CookieAppService;
@{
    ViewBag.CurrentPageName = PageNames.Blogs; // The menu item will be active for this page.
    ViewBag.Title = "Create News"; // The menu item will be active for this page.
}

<!-- #END# Widgets -->
<!-- CPU Usage -->
<div class="row clearfix">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="card">
            
            <div class="body">
                <section class="content-header">
                    
                    <div class="row">
                        <div class="col-md-6">
                            <section>
                                <h2>Create News</h2>
                            </section>

                        </div>
                        <div class="col-md-6">
                            <nav aria-label="breadcrumb" class="pull-right">
                                <ol class="breadcrumb">
                                    <li><a asp-controller="Home" asp-action="Dashboard">Home</a></li>
                                    <li><a asp-controller="Blogs" asp-action="Index">News</a></li>
                                    <li>Create News</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </section>
                <hr/>
                   <div class="modal-body">
                    <div class="row clearfix">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <article class="form-horizontal margin-top-20">
                                    <form asp-action="Create" method="post" enctype="multipart/form-data">
                                        <section class="col-md-9">

                                            <div class="input-group">
                                                <div class="col-md-3">
                                                    <label for="Title">Title</label>
                                                </div>
                                                <div class="col-md-9">
                                                    <div class="form-line">
                                                        <input type="text" required placeholder="Enter your title" id="title-textbox" asp-for="Title" maxlength="200" class="form-control"/>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="input-group">
                                                <div class="col-md-3">
                                                    <label for="Content">News Content</label>
                                                </div>
                                                <div class="col-md-9">
                                                    <div class="form-line">
                                                        <textarea required placeholder="Message" asp-for="Content" class="form-control"></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="input-group">
                                                <div class="col-md-3">
                                                    <label for="Tags">Tags</label>
                                                </div>
                                                <div class="col-md-9">
                                                    <div class="form-line">
                                                        <input placeholder="Tags" asp-for="Tags" class="form-control" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="input-group">
                                                <div class="col-md-3">
                                                    <label for="file">Image</label>
                                                </div>
                                                <div class="col-md-9">
                                                    <div class="form-line">
                                                        <input id="exampleInputFile" required="" class="form-control" name="file" type="file">
                                                        <small>Image Dimension: Width: 650, Height: 300</small>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="input-group">
                                                <div class="col-md-offset-3 col-md-9">
                                                      <input id="activateNews" type="checkbox" @(ViewBag.ActivateNews != null && (bool)ViewBag.ActivateNews ? "checked='checked'":"") name="activateNews" value="true"  class="form-control" />
                                                    <label for="activateNews" class="form-label">Activate News</label>
                                                </div>
                                                
                                            </div>
                                            <div class="input-group">
                                                <div class="col-md-9 col-md-offset-3">
                                                    <button class="btn" type="submit"> Create</button>

                                                </div>
                                            </div>

                                        </section>


                                    </form>

                    </article>
                            </div>
                        </div>
                    </div>
               
            </div>
           

                <div class="clearfix"></div>

            </div>
        </div>
    </div>
</div>

<!-- #END# CPU Usage -->

src/IContestPro.Web.Mvc/Views/Blogs/Details.cshtml
@using Abp.Runtime.Session
@using IContestPro
@using IContestPro.Blog.Dto
@using IContestPro.Cookie
@using IContestPro.Messages.Dto
@using IContestPro.Web.Helpers
@using IContestPro.Web.Startup
@using Microsoft.AspNetCore.Hosting;
@model IContestPro.Blog.Dto.BlogDtoWithDetails
@inject IHostingEnvironment HostingEnvironment;
@inject ICookieAppService CookieAppService;
@{
    ViewBag.CurrentPageName = PageNames.Blogs; // The menu item will be active for this page.
    ViewBag.Title = Model.Title; // The menu item will be active for this page.
    int pageSize = ViewBag.PageSize;
    int page = ViewBag.Page;
    Layout = "_ContestHomePageLayoutWithRightSide";

}
@section styles {
   
}


<!-- #END# Widgets -->
<!-- CPU Usage -->
<div class="clearfix">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="card">
            
                <section class="content-header">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li><a asp-controller="Home" asp-action="Dashboard">Home</a></li>
                                    <li><a asp-controller="Blogs" asp-action="Index">Blog Posts</a></li>
                                    <li>@Model.Title</li>
                                </ol>
                            </nav>
                        
                </section>
                <hr/>
                <article>
                    <article class="padding-left-20">
                        <div class="margin-bottom-30">
                            <h3>@Model.Title</h3>
                            <hr />
                            
                            <div><i class="fa fa-user"></i> <strong>@Model.Nickname</strong></div>
                            <div><i class="fa fa-calendar margin-bottom-30"></i> <strong>@Model.CreationTime.ToAppDateTimeString()</strong></div>
                           
                               <article id="st-inline-button-preview">
                    <div class="row padding-20">
                        <div class="social-button col-md-2" data-network="facebook">
                            <a href="https://www.facebook.com/sharer/sharer.php?u=@Context.Request.Scheme://@Context.Request.Host@Context.Request.Path" target="_blank">
                                <i class="fa fa-facebook social-button-icon"></i>
                                <span class="social-button-label">Facebook</span>
                            </a>
                        </div>
                        <div class="social-button  col-md-2" data-network="twitter">
                            <a href="https://twitter.com/intent/tweet?text=@Context.Request.Scheme://@Context.Request.Host@Context.Request.Path" target="_blank">
                                <i class="fa fa-twitter social-button-icon"></i>
                                <span class="social-button-label">Tweet</span>
                            </a>
                        </div>
                        <div class="social-button col-md-2" data-network="linkedin">
                            <a href="https://www.linkedin.com/shareArticle?mini=true&url=@Context.Request.Scheme://@Context.Request.Host@Context.Request.Path&title=@Model.Title&summary=@Model.Content&source=icontestpro.com" target="_blank">
                                <i class="fa fa-linkedin social-button-icon"></i>
                                <span class="social-button-label">LinkedIn</span>
                            </a>
                           
                        </div>
                        <div class="social-button col-md-2" data-network="pinterest">
                            <a href="https://pinterest.com/pin/create/button/?url=@Context.Request.Scheme://@Context.Request.Host@Context.Request.Path&media=@Context.Request.Scheme://@Context.Request.Host/images/uploads/@Model.Image&description=@Model.Content" target="_blank">
                                <i class="fa fa-pinterest social-button-icon"></i>
                                <span class="social-button-label">Pin</span>
                            </a>
                           
                        </div>
                        <div class="social-button  col-md-2" data-network="email">
                            <a href="mailto:?subject=@Model.Title&body=@Model.Content%0D%0A%0D%0A@(Context.Request.Scheme)://@Context.Request.Host@Context.Request.Path" target="_blank">
                                <i class="fa fa-envelope-o social-button-icon"></i>
                                <span class="social-button-label">Email</span>
                            </a>
                        </div>
                        
                    </div>
                </article>
                            
                            <div class="news-featured-image margin-top-20 margin-bottom-20 ">
                                <a style="display: block; width: 100%; height: 100%; background-image: url(&quot;/images/uploads/@Model.Image&quot;); background-position: top center !important;
                                           background-size: cover !important;
                                           position: relative;
                                           overflow: hidden;"> 
                                </a>
                                @*<a target="_blank" href="/images/uploads/@Model.Image"><img src="/images/uploads/@Model.Image"/></a>*@
                            </div>
                            <div class="margin-bottom-20 new-content" style="text-align: justify;">
                                <p>@Model.Content</p>
                            </div>
                        </div>
                        @if (Model.Tags != null)
                        {
                            <hr />
                            <div class="row">
                                <div class="col-md-2"> Tags</div>
                                <div class="col-md-12">
                                    @foreach (var tag in Model.Tags.Split(","))
                                    {
                                        <a asp-action="Tag" asp-route-id="@tag" title="Search tag"><span class="badge badge-danger">@tag</span></a>
                                    }
                                </div>
                            </div> 
                        }
                        
                     
                        <hr />
                        <div class="row" id="commentSection">
                            <div class="col-md-12"> <h4>Comments</h4></div>
                        </div>
                       
                        @if (Model != null &&  Model.Responses.Items.Count > 0)
                        {
                            foreach (var response in Model.Responses.Items)
                            {
                            
                                <article >
                                    <div class="row well no-margin-left no-margin-right" >
                                        <aside class="col-md-1 col-sm-1">
                                                <img src="/images/user.png" width="50" class="img-thumbnail">
                                        </aside>
                                        <section class="col-md-11  col-sm-11">
                                            <div>
                                                <h3 class="no-margin-top no-margin-bottom">@(AbpSession.UserId != null && response.UserId == AbpSession.GetUserId() ? "Me" : response.Nickname)</h3>
                                                <div>
                                                    <small class="text-muted">
                                                        <i class="fa fa-calculator"></i> @response.CreationTime.ToAppDateTimeString()</small>
                                                </div>
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="news-content">
                                                <p>@response.Message</p>    
                                            </div>
                                        </section>

                                    </div>
                                </article>
                        }
                           
                        }
                        else
                        {
                        <div class="alert alert-danger">
                                    <p class="text-danger">There are no comments for this news.</p>
                        </div>
                        }

                        <article class="form-horizontal padding-20">
                            @if (AbpSession.UserId != null)
                            {
                                <form asp-action="NewBlogResponse" id="form-close-ticket-checkbox" method="post">
                                    <div class="form-group">
                                        <input type="hidden" name="BlogId" value="@Model.Id"/>
                                        <input type="hidden" name="permalink" value="@Model.Permalink"/>
                                        <div class="form-line">
                                            <textarea placeholder="Write your comment" id="message" required name="message" class="form-control padding-10"></textarea>
                                        </div>
                                    </div> 
                                   
                                    <div class="form-group">
                                        <button class="btn" type="submit"> Comment</button>
                                    </div>
                                </form> 
                            }
                            else
                            {
                                <div class="alert alert-info">
                                    <p>Please login to post your comment. <a class="btn btn-default btn-sm" asp-action="Login", asp-controller="Account" asp-route-returnUrl="/Blogs/Details/@Model.Permalink">Login</a></p>
                                </div>  
                            }
                               

                        </article>
                        @if (Model.Responses.TotalCount > pageSize)
                        {
                            <div class="cearfix"></div>
                            <article class="margin-top-70">
                                @Html.PaginateCustomUrl(Model.Responses.TotalCount, page,
                                    pageSize, "Blogs/Details/" + Model.Permalink, "#commentSection")
                            </article>   
                        }
                        
                    </article>
                </article>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(function() {
            if(document.location.hash) {
                $('html, body').animate({
                    scrollTop: $("#commentSection").offset().top - 200
                }, 500);
            };
        });
    </script>
}
<!-- #END# CPU Usage -->