src/IContestPro.Web.Mvc/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using Abp.Dependency;
using Abp.Domain.Uow;
using Abp.Runtime.Session;
using Abp.Runtime.Validation;
using Abp.UI;
using Abp.Web.Mvc.Alerts;
using IContestPro.Contest;
using Microsoft.AspNetCore.Mvc;
using IContestPro.Messages;
using IContestPro.Messages.Dto;
using IContestPro.Web.Helpers;
using IContestPro.Web.Helpers.AlertExtension;

namespace IContestPro.Web.Controllers
{
    [AbpMvcAuthorize]
    [DisableValidation]
    public class MessagesController : BaseController
    {
        private readonly IMessagesAppService _messagesAppService;
        private readonly IContestAppService _contestAppService;
        public MessagesController( IIocResolver iocResolver, IMessagesAppService messagesAppService, IContestAppService contestAppService) : base(iocResolver)
        {
            _messagesAppService = messagesAppService;
            _contestAppService = contestAppService;
        }
        
        // GET
        public async Task<IActionResult> Index(string status = "", string fetchType = MessageFetchType.Inbox, int page = 1, int pageSize = 20)
        {
            
            var offset = (page - 1) * pageSize;  
            IReadOnlyList<UserMessageDto> items;
            const int type = MessageType.Message; 
            ViewBag.Type = type;
            ViewBag.Status = status ?? "";
            if (fetchType == MessageFetchType.Inbox)
            {
                ViewBag.InboxActive = "active";
            }else if (fetchType == MessageFetchType.Sent)
            {
                ViewBag.SentActive = "active";
            }
                 items = await _messagesAppService.GetAllByByUser(AbpSession.GetUserId(), new PagedResultRequestDto{SkipCount = offset, MaxResultCount = pageSize}, type, status, fetchType);
           var result = new AppPagedRequestResultDto<IReadOnlyList<UserMessageDto>>
           {
               Page = page,
               PageSize = pageSize,
               Result = items
           };
            return View(result); 
        } 
       
        public async Task<IActionResult> Create()
        {
            return View(new CreateMessageInputDto()); 
        } 
        
        [HttpPost]
        [UnitOfWork(false)]
        public async Task<IActionResult> Create(CreateMessageInputDto model)
        {
           try{
            if ( model.Attachments != null)
            {
                foreach (var file in model.Attachments) {
                    if (file.ContentType != "image/jpeg" && file.ContentType != "image/gif" && file.ContentType != "image/png") {
                        AddAlertMessage(new AlertMessageCustom(AlertType.Warning, "Only jgp, gif and png files are allowed."));
                        return View(model);
                    }
                }
            }
            var item = await _messagesAppService.CreateMessage(model);
            if (item != null && item.Results.Count > 0)
            {
                AddAlertMessage(new AlertMessageCustom(AlertType.Success, "Your message was sent successfully. Thank you."));
                return RedirectToAction("Index", new { type = model.MessageType });  
            }
            
                AddAlertMessage(new AlertMessageCustom(AlertType.Danger, "Error occurred while creating your message. Please try again later."));
                return View(model);   
           }
           catch (UserFriendlyException e)
           {
               AddAlertMessage(new AlertMessageCustom(AlertType.Danger, e.Message));
               return View(model); 
           }
           catch (Exception e)
           {
               AddAlertMessage(new AlertMessageCustom(AlertType.Danger, "Error occurred while processing your request."));
               return View(model);
           }
        } 
        [HttpPost]
        [UnitOfWork(false)]
        public async Task<IActionResult> CloseTicket(int messageId)
        {
           
           try{
            var item = await _messagesAppService.CloseSupportTicket(messageId);
            if (item != null)
            {
                AddAlertMessage(new AlertMessageCustom(AlertType.Success, "Support ticket closed successfully. Thank you."));
                return RedirectToAction("Details", new { id = messageId});
            }
            
                AddAlertMessage(new AlertMessageCustom(AlertType.Danger, "Error occurred while closing your ticket. Please try again later."));
            return RedirectToAction("Details", new { id = messageId});
           }
           catch (UserFriendlyException e)
           {
               AddAlertMessage(new AlertMessageCustom(AlertType.Danger, e.Message));
               return RedirectToAction("Details", new { id = messageId});
           }
           catch (Exception e)
           {
               AddAlertMessage(new AlertMessageCustom(AlertType.Danger, "Error occurred while creating advert."));
               return RedirectToAction("Details", new { id = messageId});
           }
        } 
        
        public async Task<IActionResult> Details(int id, int type)
        {
            TempData.Put("ResponseModel", new CreateMessageResponseDto());

            var item = await _messagesAppService.GetMessageDetailsWithResponses(id, type);
            return View(item); 
        } 
        
        [HttpPost]
        [UnitOfWork(false)]
        public async Task<IActionResult> Delete(int id)
        {
            await _messagesAppService.Delete(new EntityDto{Id = id});
            AddAlertMessage(new AlertMessageCustom(AlertType.Success, "Message deleted successfully. Thank you."));
            return RedirectToAction("Index");
        } 
        [HttpPost]
        [UnitOfWork(false)]
       public async Task<IActionResult> NewMessageResponse(CreateMessageResponseDto model)
        {
            try{
           TempData.Put("ResponseModel",model);;
            if (model.Attachments != null)
            {
                foreach (var file in model.Attachments) {
                    if (file.ContentType != "image/jpeg" && file.ContentType != "image/gif" && file.ContentType != "image/png") {
                        AddAlertMessage(new AlertMessageCustom(AlertType.Warning, "Only jgp, gif and png files are allowed."));
                        return RedirectToAction("Details", new { id = model.MessageId});
                    }
                }
            }
            var item = await _messagesAppService.CreateMessageResponse(model);
            if (item != null)
            {
                TempData.Remove("ResponseModel");
                AddAlertMessage(new AlertMessageCustom(AlertType.Success, "Your message response was sent successfully. Thank you."));
                return RedirectToAction("Details", new { id = model.MessageId });  
            }
            
            AddAlertMessage(new AlertMessageCustom(AlertType.Danger, "Error occurred while creating your message. Please try again later."));
            return RedirectToAction("Details", new { id = model.MessageId});
            }
            catch (UserFriendlyException e)
            {
                AddAlertMessage(new AlertMessageCustom(AlertType.Danger, e.Message));
                return RedirectToAction("Details", new { id = model.MessageId});
            }
            catch (Exception e)
            {
                AddAlertMessage(new AlertMessageCustom(AlertType.Danger, "Error occurred while creating advert."));
                return RedirectToAction("Details", new { id = model.MessageId});
            }

        } 
        public async Task<IActionResult> GetCurrentUserContests()
        {
            var items = await _contestAppService.GetAllByUserId(AbpSession.GetUserId(), new PagedResultRequestDto{SkipCount = 0, MaxResultCount = 100});
            return View("_CurrentUserContests", items);
        }
    }
}

src/IContestPro.Web.Mvc/Views/Messages/Details.cshtml
@using Abp.Runtime.Session
@using IContestPro
@using IContestPro.Cookie
@using IContestPro.Messages.Dto
@using IContestPro.Web.Helpers
@using IContestPro.Web.Startup
@using Microsoft.AspNetCore.Hosting;
@model IContestPro.Messages.Dto.UserMessageDetailsDto
@inject IHostingEnvironment HostingEnvironment;
@inject ICookieAppService CookieAppService;
@{
    ViewBag.CurrentPageName = PageNames.Messages; // The menu item will be active for this page.
}
@section styles {
    <style>
        .ticket-type-wrapper{margin: 10px 0 0 0px; min-height: 500px;background-color: #eee;}
        .ticket-type-wrapper .list-group-item:first-child{border-radius: 0; background-color: #eee;}
        .ticket-type-wrapper .list-group-item:last-child{border-radius: 0; }
    </style>
}


<!-- #END# Widgets -->
<!-- CPU Usage -->
<div class="row clearfix">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="card">
            
            <div class="body">
                <section class="content-header">
                    <div class="row">
                        <div class="col-md-6">
                            <section>
                                <h2>Message Details</h2>
                            </section>

                        </div>
                        <div class="col-md-6">
                            <nav aria-label="breadcrumb" class="pull-right">
                                <ol class="breadcrumb">
                                    <li><a asp-controller="Home" asp-action="Dashboard">Home</a></li>
                                    <li><a asp-controller="Messages" asp-action="Index">Messages</a></li>
                                    <li>Message Details</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </section>
                <hr/>
                <div class="row">
                    <aside class="col-md-2 col-xs-12 col-sm-2 no-padding-left">
                    @await Html.PartialAsync("_MessagesSideNavigation")
                </aside>
                <article class="col-md-10 col-xs-12 col-sm-10">
                    <article class="well">
                        <div class="no-margin-left no-margin-right margin-bottom-30">
                            <h3>@Model.Title</h3>
                            <div class="margin-bottom-20">@Model.MessageText</div>
                            <div><i class="fa fa-user"></i> From: <strong>@Model.FromNickName</strong></div>
                            <div><i class="fa fa-list"></i> Type: <strong>@(Model.MessageType == MessageType.Message ? "Message":"Support Ticket")</strong></div>
                            <div><i class="fa fa-thermometer"></i> Status: <strong>@Model.StatusName</strong></div>
                            <div><i class="fa fa-calendar"></i> Date: <strong>@Model.CreationTime.ToAppDateTimeString()</strong></div>
                            @if (!string.IsNullOrEmpty(Model.Attachments))
                            {
                                <hr />
                                <section class="row">
                                    @foreach (var attachment in Model.Attachments.Split(","))
                                    {
                                        <div class="col-md-2 col-lg-2 col-sm-3 col-xs-6">
                                            <a href="/images/uploads/@attachment" target="_blank"><img width="80" src="/images/uploads/@attachment" class="img-thumbnail img-responsive" /></a>
                                        </div> 
                                    }
                                </section>
                            }
                            
                        </div>
                        
                        @*
                        <hr />
@if (Model.MessageType == MessageType.SupportTicket && Model.StatusName != AppConsts.StatusClosed)
                    {
                        <section class="alert flex-container" style="background-color: #fff;">
                                <form asp-action="CloseTicket" method="post" class="form-inline flex-item" style="display: inline-block; margin-top: 25px;">
                                    <input type="hidden" name="messageId" value="@Model.Id"/>
                                    <div class="input-group">
                                        <button class="btn btn-success-inverse btn-block btn-close-ticket" type="submit"> Close Ticket</button>
                                    </div>
                                </form>
                        </section>
                    }*@
                        <hr />
                        <div class="row">
                            <div class="col-md-12"> <h4>Responses</h4></div>
                        </div>
                        @foreach (var response in Model.Responses)
                        {
                            
                                <article >
                                    <div class="row @((response.UserId != AbpSession.GetUserId()) ? "well no-margin-left no-margin-right" : "")" style="@((response.UserId != AbpSession.GetUserId()) ? "" : "background-color: #fff; margin: 10px 0; padding: 10px;border-radius: 4px;")">
                                        <aside class="col-md-2 col-sm-2 col-xs-2">
                                            @if (!string.IsNullOrEmpty(response.UserImage))
                                            {
                                                <img src="/images/uploads/@response.UserImage" width="50"
                                                     class="img-thumbnail" >
                                            }
                                            else
                                            {
                                                <img src="/images/user.png" width="50" class="img-thumbnail">
                                            }
                                        </aside>
                                        <section class="col-md-10  col-sm-10 col-xs-10">
                                            <div>
                                                <h3 class="no-margin-top">@(response.UserId == AbpSession.GetUserId() ? "Me" : response.UserNickName)</h3>
                                                <div>
                                                    <small class="text-muted">
                                                        <i class="fa fa-calculator"></i> @response.CreationTime.ToAppDateTimeString()</small>
                                                </div>
                                            </div>
                                            <div class="clearfix"></div>
                                            <p>@response.Message</p>
                                            @if (!string.IsNullOrEmpty(response.Attachments)){
                                            <hr/>
                                            <section class="row">
                                                @foreach (var attachment in response.Attachments.Split(",")){
                                                <div class="col-md-3 col-lg-3 col-sm-3 col-xs-6">
                                                    <a href="/images/uploads/@attachment" target="_blank"><img width="80" src="/images/uploads/@attachment" class="img-thumbnail img-responsive"/></a>
                                                </div>
                                                }
                                            </section>
                                            }
                                        </section>

                                    </div>
                                </article>
                        }
                        @if(Model.StatusName != AppConsts.StatusClosed)
                        {
                            var responseModel = TempData.Get<CreateMessageResponseDto>("ResponseModel");
                            <article class="form-horizontal">
                                <form asp-action="NewMessageResponse" id="form-close-ticket-checkbox" method="post" enctype="multipart/form-data">
                                    <div class="input-group">
                                        <input type="hidden" name="MessageId" value="@Model.Id"/>
                                        <input type="hidden" name="MessageSenderUserId" value="@Model.FromUserId"/>
                                        <input type="hidden" name="MessageType" value="@Model.MessageType"/>
                                        <div class="form-line">
                                            <textarea placeholder="@(Model.MessageType == MessageType.Message ? "Write your reply message":"Write your response for this ticket")" id="message" required name="message" class="form-control">@responseModel.Message</textarea>
                                        </div>
                                    </div> 
                                    <div class="input-group">
                                        <label for="exampleInputFile">Attachments</label>
                                        <input id="exampleInputFile" name="Attachments" type="file" multiple>
                                    </div>
                                    @if (Model.MessageType == MessageType.SupportTicket && Model.StatusName != AppConsts.StatusClosed)
                                    {
                                        <div class="input-group">
                                            <label>
                                                <input type="checkbox" id="close-ticket-checkbox" name="CloseTicket" value="true" style="position: static; opacity: 1;"/>
                                                <input type="hidden" name="CloseTicket" value="false"/>
                                                Close Ticket
                                            </label>

                                        </div>  
                                    }
                                    <div class="input-group">
                                            <button class="btn btn-close-ticket-checkbox" type="submit"> Reply</button>
                                    </div>
                                </form>

                            </article>
                       }
                        
                        
                    </article>
                </article>
                </div>

                <div class="clearfix"></div>

            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script>
        $(function() {
            $('.btn-close-ticket').click(function(e) {
                var element = $(this);
                e.preventDefault();
                abp.message.confirm("Are you sure you want to mark this ticket closed? Remember, no further communication is allowed on closed ticket.", 
                    function(result) {
                        if (result) {
                            element.closest('form').submit();
                        }
                    });
            });
            var askedToCloseTicket = false;
            $('#form-close-ticket-checkbox').submit(function(e) {
                var element = $(this);
                if (!askedToCloseTicket) {
                    if ($('#close-ticket-checkbox').prop('checked') === true) {
                        askedToCloseTicket = true;
                        e.preventDefault();
                        abp.message.confirm("Are you sure you want to mark this ticket closed? Remember, no further communication is allowed on closed ticket.", 
                            function(result) {
                                if (result) {
                                    element.submit();
                                } else {
                                    askedToCloseTicket = false;
                                }
                            });  
                    }  
                }
                
            });
        });
    </script>
}
<!-- #END# CPU Usage -->

src/IContestPro.Web.Mvc/Views/Messages/Index.cshtml
@using Abp.Runtime.Session
@using IContestPro
@using IContestPro.Cookie
@using IContestPro.Web.Helpers
@using IContestPro.Web.Startup
@using Microsoft.AspNetCore.Hosting;
@model AppPagedRequestResultDto<IReadOnlyList<IContestPro.Messages.Dto.UserMessageDto>>
@inject IHostingEnvironment HostingEnvironment;
@inject ICookieAppService CookieAppService;
@{
    ViewBag.CurrentPageName = PageNames.Messages; // The menu item will be active for this page.
}
@section styles {
   
}

<!-- #END# Widgets -->
<!-- CPU Usage -->
<div class="row clearfix">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="card">
            
            <div class="body">
                <section class="content-header">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-6">
                            <nav aria-label="breadcrumb" class="pull-right">
                                <ol class="breadcrumb">
                                    <li><a asp-controller="Home" asp-action="Dashboard">Home</a></li>
                                    <li>Messages</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                    <section>
                        <h2>Messages <a asp-action="Create" class="btn pull-right">New Message</a></h2>

                    </section>

                </section>
                <hr/>
                <div class="row">
                    <aside class="col-md-2 col-sm-2 col-xs-12 no-padding-left">
                    @await Html.PartialAsync("_MessagesSideNavigation")
                </aside>
                <article class="col-md-10  col-sm-10 col-xs-12">
                    <section class="table-responsive">
                       

                        @{
                            var row = ((Model.Page - 1) * Model.PageSize) + 1;
                        }
                        @if (Model.Result != null && Model.Result.Count > 0)
                        {
                            <table id="tickets-table" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>S/N</th>
                                    <th>From</th>
                                    <th>To</th>
                                    <th>Title</th>
                                    <th>Status</th>
                                    <th>Type</th>
                                    <th>Date</th>
                                    <th>Attachments</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach (var message in Model.Result)
                                {
                                    <tr class="@(message.StatusName == AppConsts.StatusNew ? "new-message-row":"")">
                                        <td>@row
                                            @if (message.StatusName == AppConsts.StatusNew)
                                            {
                                                <span class="unread"></span>   
                                            }
                                            </td>
                                        <td>
                                            @if (message.FromUserId == AbpSession.GetUserId())
                                            {
                                                <span>Me</span>
                                            }
                                            else
                                            {
                                                <span>@message.FromNickName</span>
                                            }
                                        </td>
                                        <td>
                                            @if (message.ToUserId == AbpSession.GetUserId())
                                            {
                                                <span>Me</span>
                                            }
                                            else
                                            {
                                                <span>@message.ToNickName</span>
                                            }
                                        </td>
                                        <td><a asp-action="Details" asp-route-id="@message.Id" asp-route-type="@message.MessageType">@message.Title</a></td>
                                        <td>@message.StatusName</td>
                                        <td>@message.MessageType.GetMessageTypeName()</td>
                                        <td>@message.CreationTime.ToAppDateTimeString()</td>
                                        @if (!string.IsNullOrEmpty(message.Attachments))
                                        {
                                            <td>@message.Attachments.Split(",").Length</td>
                                        }
                                        else
                                        {
                                            <td>None</td>
                                        }
                                        <td class="dropdown">
                                        @if (message.MessageType == MessageType.Message && message.ToUserId == AbpSession.GetUserId())
                                        {
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                                <i class="material-icons">menu</i>
                                            </a>
                                            <ul class="dropdown-menu pull-right">
                                                <li>
                                                    <form asp-action="Delete" method="post" class="form-inline flex-item" style="display: inline-block; margin-top: 25px; width: 100%;">
                                                        <input type="hidden" name="id" value="@message.Id"/>
                                                        <div class="input-group">
                                                            <button class="btn-block delete-item btn-link"><i class="fa fa-trash"></i> @L("Delete")</button>
                                                        </div>
                                                    </form>
                                                </li>
                                            </ul>
                                        }
                                            
                                        </td>
                                    </tr>
                                    row++;
                                }
                                </tbody>
                            </table>
                            <article>
                                @{
                                    var type = (int)ViewBag.Type;
                                    var statusName = (string)ViewBag.Status;
                                }
                                @Html.PaginateAdmin(Model.Result.First().TotalItemsCount, Model.Page,
                                    Model.PageSize, "Messages", "Index",
                                    "type=" + type + (!string.IsNullOrEmpty(statusName) ? $"&status={statusName}": ""))
                            </article>
                        }
                        else
                        {
                            <div>
                                <div class="alert alert-info">
                                    <h3>There are no messages.</h3></div>
                            </div>
                        }
                        <!-- /.box -->


                    </section>
                </article>
                </div>

                <div class="clearfix"></div>

            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script>
        $(function() {
            $('.delete-item').click(function(e) {
                var element = $(this);
                e.preventDefault();
                abp.message.confirm("Are you sure you want to delete? Remember, deletion is permanent.", 
                    function(result) {
                        if (result) {
                            element.closest('form').submit();
                        }
                    });
            });
        });
    </script>
}

<!-- #END# CPU Usage -->

src/IContestPro.Web.Mvc/Views/Messages/_CurrentUserContests.cshtml
@using Microsoft.AspNetCore.Hosting
@model Abp.Application.Services.Dto.PagedResultDto<IContestPro.Contest.Dto.ContestDto>
@inject IHostingEnvironment HostingEnvironment

@{
    Layout = null;
}
<select required="" class="form-control" id="ContestId" name="ContestId">
        @if (Model != null && Model.Items.Any())
        { 
                foreach (var item in Model.Items)
                {
                    <option value="@item.Id">@item.Title</option>
                }

        }
        else
        {
            <option selected="selected" value="">You do not have any contest</option>
        }
</select>